; ── PHP configuration – développement ──────────────────────────
[PHP]
display_errors       = On
display_startup_errors = On
error_reporting      = E_ALL & ~E_WARNING
log_errors           = On
sys_temp_dir         = /var/www/html/storage/framework/temp
upload_tmp_dir       = /var/www/html/storage/framework/temp

memory_limit         = 512M
max_execution_time   = 120
upload_max_filesize  = 50M
post_max_size        = 50M

[opcache]
opcache.enable           = 0

[xdebug]
xdebug.mode          = debug
xdebug.start_with_request = yes
xdebug.client_host   = host.docker.internal
xdebug.client_port   = 9003
xdebug.log_level     = 0
